In [1]:
#Import all required libraries
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('/content/sample_data/UpdatedResumeDataSet.csv',encoding='utf-8')
df.head()

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...

In [3]:
print('\n Columns',df.columns.tolist())

 Columns ['Category', 'Resume']

In [5]:
sample_df=df.sample(10,random_state=42).reset_index(drop=True)
sample_df
print(sample_df.shape)

(10, 2)

In [6]:
vectorizer=TfidfVectorizer(stop_words='english')
tfidf_matrix=vectorizer.fit_transform(sample_df['Resume'])
tfidf_matrix.shape

(10, 1125)

In [8]:
similartiness_matrix=cosine_similarity(tfidf_matrix)
sim_df=pd.DataFrame(similartiness_matrix,index=sample_df['Category']+"__"+sample_df.index.astype(str),
                    columns=sample_df['Category']+"__"+sample_df.index.astype(str))
sim_df.round(2).head(3)

,Java Developer__0,Java Developer__1,Java Developer__2,Hadoop__3,Health and fitness__4,Network Security Engineer__5,Mechanical Engineer__6,Automation Testing__7,Advocate__8,Health and fitness__9
Java Developer__0,1.00,0.41,0.24,0.11,0.06,0.07,0.06,0.10,0.11,0.08
Java Developer__1,0.41,1.00,0.22,0.14,0.03,0.05,0.03,0.09,0.09,0.06
Java Developer__2,0.24,0.22,1.00,0.11,0.07,0.07,0.07,0.08,0.05,0.03

In [9]:
resumes={
    "candidate":['Sam','Arsh','Maan'],
    "resume_text":["Python developer skilled in Django,Flask, Rest API and MySql",
                   "Machine learning engineer experience in Python,TensorFlow,NLP and data analysis",
                   "Full stack developer with .net,javascript, React, Node.js and MongoDB experience"]
}

In [11]:
df=pd.DataFrame(resumes)
df

  candidate                                        resume_text
0       Sam  Python developer skilled in Django,Flask, Rest...
1      Arsh  Machine learning engineer experience in Python...
2      Maan  Full stack developer with .net,javascript, Rea...

In [12]:
vectorizer=TfidfVectorizer(stop_words='english')
tfidf_matrix=vectorizer.fit_transform(df['resume_text'])
tfidf_matrix.shape
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 26 stored elements and shape (3, 23)>

In [13]:
similartiness_matrix=cosine_similarity(tfidf_matrix)
sim_df=pd.DataFrame(similartiness_matrix,index=df['candidate'],
                    columns=df['candidate'])
sim_df.round(2)

candidate   Sam  Arsh  Maan
candidate
Sam        1.00  0.08  0.08
Arsh       0.08  1.00  0.07
Maan       0.08  0.07  1.00

In [14]:
df.loc[len(df)]=["Zoya","Backend developer skilled in Python, Flask and SQL"]

In [15]:
df

  candidate                                        resume_text
0       Sam  Python developer skilled in Django,Flask, Rest...
1      Arsh  Machine learning engineer experience in Python...
2      Maan  Full stack developer with .net,javascript, Rea...
3      Zoya  Backend developer skilled in Python, Flask and...

In [17]:
vectorizer=TfidfVectorizer(stop_words='english')
tfidf_matrix=vectorizer.fit_transform(df['resume_text'])
tfidf_matrix.shape
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 32 stored elements and shape (4, 25)>

In [18]:
similartiness_matrix=cosine_similarity(tfidf_matrix)
sim_df=pd.DataFrame(similartiness_matrix,index=df['candidate'],
                    columns=df['candidate'])
sim_df.round(2)

candidate   Sam  Arsh  Maan  Zoya
candidate
Sam        1.00  0.06  0.06  0.42
Arsh       0.06  1.00  0.08  0.07
Maan       0.06  0.08  1.00  0.07
Zoya       0.42  0.07  0.07  1.00