**Steps for model:**



1.   Creating the model
2.   Compiling the model
3. Define a loss further
4. Setting up an optimizer
5. Finding best learning size
6. Creating evaluation metrics'
7. Fitting model
8. Improve model

# Predict heart disease


1.   Load dataset
2.   Split features and test
3. Train test split

In [15]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [ ]:
heart_data=pd.read_csv('/content/sample_data/heart.csv')
heart_data.head()

   age  sex  chol  trestbps  thalach  target
0   52    1   200       130      150       1
1   58    0   240       150      140       1
2   60    1   180       140      145       0
3   48    1   190       120      160       0
4   50    0   220       125      155       1

In [ ]:
X=heart_data.drop('target',axis=1)
y=heart_data['target']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
# Create the model
model=tf.keras.Sequential(
    [
      tf.keras.layers.Dense(16,activation='relu',input_shape=(X_train.shape[1],)),
      tf.keras.layers.Dense(8,activation='relu'),
      tf.keras.layers.Dense(1,activation='sigmoid')

    ]
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
#train the model
history_model=model.fit(X_train,y_train,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.3750 - loss: 0.8550 - val_accuracy: 0.5000 - val_loss: 0.6335
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - accuracy: 0.3750 - loss: 0.8468 - val_accuracy: 0.5000 - val_loss: 0.6307
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step - accuracy: 0.3750 - loss: 0.8388 - val_accuracy: 0.5000 - val_loss: 0.6279
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 248ms/step - accuracy: 0.3750 - loss: 0.8308 - val_accuracy: 0.5000 - val_loss: 0.6252
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 260ms/step - accuracy: 0.3750 - loss: 0.8230 - val_accuracy: 0.5000 - val_loss: 0.6229
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step - accuracy: 0.3750 - loss: 0.8153 - val_accuracy: 0.5000 - val_loss: 0.6212
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 250ms/step - accuracy: 0.3750 - loss: 0.8077 - val_accuracy: 0.5000 - val_loss: 0.6195
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 236ms/step - accuracy: 0.3750 - loss: 0.8002 - val_accuracy: 0.5000 - val_loss: 0.6180
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 296ms/step - accuracy: 0.3750 - loss: 0.7928 - val_accuracy: 0.5000 - val_loss: 0.6165
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - accuracy: 0.3750 - loss: 0.7855 - val_accuracy: 0.5000 - val_loss: 0.6151
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 321ms/step - accuracy: 0.3750 - loss: 0.7784 - val_accuracy: 0.5000 - val_loss: 0.6138
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 320ms/step - accuracy: 0.3750 - loss: 0.7713 - val_accuracy: 0.5000 - val_loss: 0.6126
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 491ms/step - accuracy: 0.3750 - loss: 0.7644 - val_accuracy: 0.5000 - val_loss: 0.6117
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 296ms/step - accuracy: 0.3750 - loss: 0.7575 - val_accuracy: 0.5000 - val_loss: 0.6106
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 357ms/step - accuracy: 0.3750 - loss: 0.7508 - val_accuracy: 0.5000 - val_loss: 0.6096
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 359ms/step - accuracy: 0.3750 - loss: 0.7442 - val_accuracy: 0.5000 - val_loss: 0.6086
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 242ms/step - accuracy: 0.2500 - loss: 0.7376 - val_accuracy: 0.5000 - val_loss: 0.6077
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 282ms/step - accuracy: 0.2500 - loss: 0.7312 - val_accuracy: 0.5000 - val_loss: 0.6067
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 360ms/step - accuracy: 0.2500 - loss: 0.7249 - val_accuracy: 0.5000 - val_loss: 0.6059
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 313ms/step - accuracy: 0.2500 - loss: 0.7187 - val_accuracy: 0.5000 - val_loss: 0.6050
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 316ms/step - accuracy: 0.2500 - loss: 0.7126 - val_accuracy: 0.5000 - val_loss: 0.6042
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 338ms/step - accuracy: 0.2500 - loss: 0.7065 - val_accuracy: 0.5000 - val_loss: 0.6034
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 569ms/step - accuracy: 0.3750 - loss: 0.7006 - val_accuracy: 0.5000 - val_loss: 0.6027
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 291ms/step - accuracy: 0.3750 - loss: 0.6947 - val_accuracy: 0.5000 - val_loss: 0.6019
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 414ms/step - accuracy: 0.5000 - loss: 0.6890 - val_accuracy: 0.5000 - val_loss: 0.6012
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 492ms/step - accuracy: 0.5000 - loss: 0.6833 - val_accuracy: 0.5000 - val_loss: 0.6006
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 315ms/step - accuracy: 0.5000 - loss: 0.6777 - val_accuracy: 0.5000 - val_loss: 0.5998
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step - accuracy: 0.5000 - loss: 0.6723 - val_accuracy: 1.0000 - val_loss: 0.5988
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 274ms/step - accuracy: 0.5000 - loss: 0.6670 - val_accuracy: 1.0000 - val_loss: 0.5977
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - accuracy: 0.5000 - loss: 0.6617 - val_accuracy: 1.0000 - val_loss: 0.5966
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - accuracy: 0.5000 - loss: 0.6566 - val_accuracy: 1.0000 - val_loss: 0.5953
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - accuracy: 0.6250 - loss: 0.6516 - val_accuracy: 1.0000 - val_loss: 0.5940
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6250 - loss: 0.6468 - val_accuracy: 1.0000 - val_loss: 0.5927
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.6250 - loss: 0.6421 - val_accuracy: 1.0000 - val_loss: 0.5915
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6250 - loss: 0.6375 - val_accuracy: 1.0000 - val_loss: 0.5904
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6250 - loss: 0.6329 - val_accuracy: 1.0000 - val_loss: 0.5893
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.6250 - loss: 0.6284 - val_accuracy: 1.0000 - val_loss: 0.5883
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6250 - loss: 0.6239 - val_accuracy: 1.0000 - val_loss: 0.5873
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.6250 - loss: 0.6194 - val_accuracy: 1.0000 - val_loss: 0.5864
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.6250 - loss: 0.6153 - val_accuracy: 1.0000 - val_loss: 0.5856
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.6250 - loss: 0.6111 - val_accuracy: 1.0000 - val_loss: 0.5849
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.6250 - loss: 0.6074 - val_accuracy: 1.0000 - val_loss: 0.5843
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6250 - loss: 0.6039 - val_accuracy: 1.0000 - val_loss: 0.5837
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.6250 - loss: 0.6004 - val_accuracy: 1.0000 - val_loss: 0.5831
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6250 - loss: 0.5969 - val_accuracy: 1.0000 - val_loss: 0.5826
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.6250 - loss: 0.5936 - val_accuracy: 1.0000 - val_loss: 0.5821
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.6250 - loss: 0.5902 - val_accuracy: 1.0000 - val_loss: 0.5815
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6250 - loss: 0.5870 - val_accuracy: 1.0000 - val_loss: 0.5810
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.7500 - loss: 0.5837 - val_accuracy: 1.0000 - val_loss: 0.5803
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.7500 - loss: 0.5805 - val_accuracy: 1.0000 - val_loss: 0.5796
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.7500 - loss: 0.5773 - val_accuracy: 1.0000 - val_loss: 0.5789
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.7500 - loss: 0.5741 - val_accuracy: 1.0000 - val_loss: 0.5783
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.8750 - loss: 0.5709 - val_accuracy: 1.0000 - val_loss: 0.5776
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.8750 - loss: 0.5679 - val_accuracy: 1.0000 - val_loss: 0.5769
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.5649 - val_accuracy: 1.0000 - val_loss: 0.5763
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 1.0000 - loss: 0.5620 - val_accuracy: 1.0000 - val_loss: 0.5757
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.5591 - val_accuracy: 1.0000 - val_loss: 0.5753
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.5562 - val_accuracy: 1.0000 - val_loss: 0.5749
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.5532 - val_accuracy: 1.0000 - val_loss: 0.5746
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.5501 - val_accuracy: 1.0000 - val_loss: 0.5743
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.5471 - val_accuracy: 1.0000 - val_loss: 0.5741
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.5441 - val_accuracy: 1.0000 - val_loss: 0.5739
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 1.0000 - loss: 0.5411 - val_accuracy: 1.0000 - val_loss: 0.5738
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.5381 - val_accuracy: 1.0000 - val_loss: 0.5736
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 1.0000 - loss: 0.5352 - val_accuracy: 1.0000 - val_loss: 0.5734
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 1.0000 - loss: 0.5322 - val_accuracy: 1.0000 - val_loss: 0.5732
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - accuracy: 1.0000 - loss: 0.5293 - val_accuracy: 1.0000 - val_loss: 0.5731
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - accuracy: 1.0000 - loss: 0.5264 - val_accuracy: 1.0000 - val_loss: 0.5731
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 1.0000 - loss: 0.5234 - val_accuracy: 1.0000 - val_loss: 0.5732
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - accuracy: 1.0000 - loss: 0.5204 - val_accuracy: 1.0000 - val_loss: 0.5732
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 281ms/step - accuracy: 1.0000 - loss: 0.5174 - val_accuracy: 1.0000 - val_loss: 0.5734
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - accuracy: 1.0000 - loss: 0.5143 - val_accuracy: 1.0000 - val_loss: 0.5736
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 273ms/step - accuracy: 1.0000 - loss: 0.5113 - val_accuracy: 1.0000 - val_loss: 0.5739
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 1.0000 - loss: 0.5082 - val_accuracy: 1.0000 - val_loss: 0.5741
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 338ms/step - accuracy: 1.0000 - loss: 0.5052 - val_accuracy: 1.0000 - val_loss: 0.5743
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 228ms/step - accuracy: 1.0000 - loss: 0.5020 - val_accuracy: 1.0000 - val_loss: 0.5745
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.4989 - val_accuracy: 1.0000 - val_loss: 0.5748
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.4957 - val_accuracy: 1.0000 - val_loss: 0.5752
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 1.0000 - loss: 0.4926 - val_accuracy: 1.0000 - val_loss: 0.5756
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.4894 - val_accuracy: 1.0000 - val_loss: 0.5760
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 1.0000 - loss: 0.4863 - val_accuracy: 1.0000 - val_loss: 0.5764
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.4832 - val_accuracy: 1.0000 - val_loss: 0.5766
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.4801 - val_accuracy: 1.0000 - val_loss: 0.5768
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.4770 - val_accuracy: 1.0000 - val_loss: 0.5772
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.4739 - val_accuracy: 1.0000 - val_loss: 0.5775
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.4708 - val_accuracy: 1.0000 - val_loss: 0.5780
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.4677 - val_accuracy: 1.0000 - val_loss: 0.5784
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.4646 - val_accuracy: 1.0000 - val_loss: 0.5789
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.4615 - val_accuracy: 1.0000 - val_loss: 0.5792
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.4583 - val_accuracy: 1.0000 - val_loss: 0.5792
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 1.0000 - loss: 0.4551 - val_accuracy: 0.5000 - val_loss: 0.5787
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 1.0000 - loss: 0.4517 - val_accuracy: 0.5000 - val_loss: 0.5784
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.4482 - val_accuracy: 0.5000 - val_loss: 0.5780
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.4447 - val_accuracy: 0.5000 - val_loss: 0.5777
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.4411 - val_accuracy: 0.5000 - val_loss: 0.5774
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.4374 - val_accuracy: 0.5000 - val_loss: 0.5772
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.4337 - val_accuracy: 0.5000 - val_loss: 0.5769
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.4299 - val_accuracy: 0.5000 - val_loss: 0.5764
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.4262 - val_accuracy: 0.5000 - val_loss: 0.5760
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.4224 - val_accuracy: 0.5000 - val_loss: 0.5756

In [ ]:
# evaluate the model
loss,accuracy=model.evaluate(X_test,y_test)
print(f'Loss:{loss},Accuracy:{accuracy}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.5000 - loss: 0.5756
Loss:0.575621485710144,Accuracy:0.5

Example 2

Bank customer
*   List item
*   List item

In [12]:
#Example
bank_data=pd.read_csv('/content/sample_data/bank_churn.csv')
bank_data.head()

,CreditScore,Geography,Gender,Age,Balance,NumOfProducts,EstimatedSalary,Exited
0,600,France,Male,40,60000,1,50000,0
1,700,Spain,Female,45,70000,2,60000,0
2,800,Germany,Female,38,80000,1,70000,1
3,400,France,Male,30,30000,1,40000,1
4,550,Spain,Male,50,40000,2,42000,0

In [16]:
le=LabelEncoder()
bank_data['Gender']=le.fit_transform(bank_data['Gender'])
bank_data=pd.get_dummies(bank_data,columns=['Geography'])
X=bank_data.drop('Exited',axis=1)
y=bank_data['Exited']

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [18]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [21]:
# Create the model
bank_model=tf.keras.Sequential(
    [
      tf.keras.layers.Dense(16,activation='relu',input_shape=(X_train.shape[1],)),
      tf.keras.layers.Dense(8,activation='relu'),
      tf.keras.layers.Dense(1,activation='sigmoid')

    ]
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [23]:
bank_model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
#bank_model.summary()

In [25]:
#train the model
bank_model_history=bank_model.fit(X_train,y_train,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 492ms/step - accuracy: 1.0000 - loss: 0.3887 - val_accuracy: 0.5000 - val_loss: 0.8152
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 521ms/step - accuracy: 1.0000 - loss: 0.3857 - val_accuracy: 0.5000 - val_loss: 0.8182
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 328ms/step - accuracy: 1.0000 - loss: 0.3826 - val_accuracy: 0.5000 - val_loss: 0.8207
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step - accuracy: 1.0000 - loss: 0.3794 - val_accuracy: 0.5000 - val_loss: 0.8235
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 336ms/step - accuracy: 1.0000 - loss: 0.3764 - val_accuracy: 0.5000 - val_loss: 0.8265
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 441ms/step - accuracy: 1.0000 - loss: 0.3733 - val_accuracy: 0.5000 - val_loss: 0.8297
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 305ms/step - accuracy: 1.0000 - loss: 0.3702 - val_accuracy: 0.5000 - val_loss: 0.8331
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 365ms/step - accuracy: 1.0000 - loss: 0.3671 - val_accuracy: 0.5000 - val_loss: 0.8367
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 621ms/step - accuracy: 1.0000 - loss: 0.3641 - val_accuracy: 0.5000 - val_loss: 0.8400
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 302ms/step - accuracy: 1.0000 - loss: 0.3610 - val_accuracy: 0.5000 - val_loss: 0.8431
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 388ms/step - accuracy: 1.0000 - loss: 0.3580 - val_accuracy: 0.5000 - val_loss: 0.8461
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 322ms/step - accuracy: 1.0000 - loss: 0.3549 - val_accuracy: 0.5000 - val_loss: 0.8491
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 292ms/step - accuracy: 1.0000 - loss: 0.3519 - val_accuracy: 0.5000 - val_loss: 0.8524
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 326ms/step - accuracy: 1.0000 - loss: 0.3489 - val_accuracy: 0.5000 - val_loss: 0.8559
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 320ms/step - accuracy: 1.0000 - loss: 0.3460 - val_accuracy: 0.5000 - val_loss: 0.8596
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 285ms/step - accuracy: 1.0000 - loss: 0.3429 - val_accuracy: 0.5000 - val_loss: 0.8634
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 396ms/step - accuracy: 1.0000 - loss: 0.3399 - val_accuracy: 0.5000 - val_loss: 0.8667
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - accuracy: 1.0000 - loss: 0.3366 - val_accuracy: 0.5000 - val_loss: 0.8700
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - accuracy: 1.0000 - loss: 0.3332 - val_accuracy: 0.5000 - val_loss: 0.8736
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 1.0000 - loss: 0.3299 - val_accuracy: 0.5000 - val_loss: 0.8776
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 343ms/step - accuracy: 1.0000 - loss: 0.3266 - val_accuracy: 0.5000 - val_loss: 0.8819
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - accuracy: 1.0000 - loss: 0.3233 - val_accuracy: 0.5000 - val_loss: 0.8862
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.3200 - val_accuracy: 0.5000 - val_loss: 0.8897
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - accuracy: 1.0000 - loss: 0.3167 - val_accuracy: 0.5000 - val_loss: 0.8933
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 268ms/step - accuracy: 1.0000 - loss: 0.3136 - val_accuracy: 0.5000 - val_loss: 0.8975
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 411ms/step - accuracy: 1.0000 - loss: 0.3105 - val_accuracy: 0.5000 - val_loss: 0.9021
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 286ms/step - accuracy: 1.0000 - loss: 0.3071 - val_accuracy: 0.5000 - val_loss: 0.9072
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 338ms/step - accuracy: 1.0000 - loss: 0.3036 - val_accuracy: 0.5000 - val_loss: 0.9120
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 548ms/step - accuracy: 1.0000 - loss: 0.3001 - val_accuracy: 0.5000 - val_loss: 0.9168
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 288ms/step - accuracy: 1.0000 - loss: 0.2966 - val_accuracy: 0.5000 - val_loss: 0.9215
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 322ms/step - accuracy: 1.0000 - loss: 0.2931 - val_accuracy: 0.5000 - val_loss: 0.9266
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 548ms/step - accuracy: 1.0000 - loss: 0.2896 - val_accuracy: 0.5000 - val_loss: 0.9316
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 197ms/step - accuracy: 1.0000 - loss: 0.2860 - val_accuracy: 0.5000 - val_loss: 0.9366
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accuracy: 1.0000 - loss: 0.2825 - val_accuracy: 0.5000 - val_loss: 0.9418
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step - accuracy: 1.0000 - loss: 0.2790 - val_accuracy: 0.5000 - val_loss: 0.9469
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - accuracy: 1.0000 - loss: 0.2756 - val_accuracy: 0.5000 - val_loss: 0.9515
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - accuracy: 1.0000 - loss: 0.2721 - val_accuracy: 0.5000 - val_loss: 0.9566
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 1.0000 - loss: 0.2686 - val_accuracy: 0.5000 - val_loss: 0.9619
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - accuracy: 1.0000 - loss: 0.2653 - val_accuracy: 0.5000 - val_loss: 0.9671
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 327ms/step - accuracy: 1.0000 - loss: 0.2620 - val_accuracy: 0.5000 - val_loss: 0.9725
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - accuracy: 1.0000 - loss: 0.2587 - val_accuracy: 0.5000 - val_loss: 0.9777
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - accuracy: 1.0000 - loss: 0.2555 - val_accuracy: 0.5000 - val_loss: 0.9829
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 1.0000 - loss: 0.2522 - val_accuracy: 0.5000 - val_loss: 0.9885
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 449ms/step - accuracy: 1.0000 - loss: 0.2491 - val_accuracy: 0.5000 - val_loss: 0.9942
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step - accuracy: 1.0000 - loss: 0.2460 - val_accuracy: 0.5000 - val_loss: 0.9999
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - accuracy: 1.0000 - loss: 0.2430 - val_accuracy: 0.5000 - val_loss: 1.0053
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - accuracy: 1.0000 - loss: 0.2399 - val_accuracy: 0.5000 - val_loss: 1.0105
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 299ms/step - accuracy: 1.0000 - loss: 0.2370 - val_accuracy: 0.5000 - val_loss: 1.0160
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 1.0000 - loss: 0.2340 - val_accuracy: 0.5000 - val_loss: 1.0219
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.2311 - val_accuracy: 0.5000 - val_loss: 1.0277
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 1.0000 - loss: 0.2283 - val_accuracy: 0.5000 - val_loss: 1.0334
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 1.0000 - loss: 0.2255 - val_accuracy: 0.5000 - val_loss: 1.0394
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 1.0000 - loss: 0.2227 - val_accuracy: 0.5000 - val_loss: 1.0457
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.2199 - val_accuracy: 0.5000 - val_loss: 1.0522
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.2171 - val_accuracy: 0.5000 - val_loss: 1.0581
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 1.0000 - loss: 0.2144 - val_accuracy: 0.5000 - val_loss: 1.0637
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.2118 - val_accuracy: 0.5000 - val_loss: 1.0692
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.2093 - val_accuracy: 0.5000 - val_loss: 1.0753
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.2068 - val_accuracy: 0.5000 - val_loss: 1.0817
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.2041 - val_accuracy: 0.5000 - val_loss: 1.0884
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 1.0000 - loss: 0.2015 - val_accuracy: 0.5000 - val_loss: 1.0951
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.1990 - val_accuracy: 0.5000 - val_loss: 1.1014
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.1965 - val_accuracy: 0.5000 - val_loss: 1.1075
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.1941 - val_accuracy: 0.5000 - val_loss: 1.1138
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.1916 - val_accuracy: 0.5000 - val_loss: 1.1203
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.1892 - val_accuracy: 0.5000 - val_loss: 1.1271
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.1868 - val_accuracy: 0.5000 - val_loss: 1.1340
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.1845 - val_accuracy: 0.5000 - val_loss: 1.1403
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.1822 - val_accuracy: 0.5000 - val_loss: 1.1460
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.1799 - val_accuracy: 0.5000 - val_loss: 1.1521
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 1.0000 - loss: 0.1777 - val_accuracy: 0.5000 - val_loss: 1.1586
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.1755 - val_accuracy: 0.5000 - val_loss: 1.1654
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 1.0000 - loss: 0.1734 - val_accuracy: 0.5000 - val_loss: 1.1720
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.1712 - val_accuracy: 0.5000 - val_loss: 1.1784
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 1.0000 - loss: 0.1691 - val_accuracy: 0.5000 - val_loss: 1.1845
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.1670 - val_accuracy: 0.5000 - val_loss: 1.1908
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.1649 - val_accuracy: 0.5000 - val_loss: 1.1970
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step - accuracy: 1.0000 - loss: 0.1629 - val_accuracy: 0.5000 - val_loss: 1.2035
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 214ms/step - accuracy: 1.0000 - loss: 0.1609 - val_accuracy: 0.5000 - val_loss: 1.2103
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.1589 - val_accuracy: 0.5000 - val_loss: 1.2172
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 1.0000 - loss: 0.1571 - val_accuracy: 0.5000 - val_loss: 1.2234
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.1552 - val_accuracy: 0.5000 - val_loss: 1.2292
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 1.0000 - loss: 0.1532 - val_accuracy: 0.5000 - val_loss: 1.2351
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 1.0000 - loss: 0.1514 - val_accuracy: 0.5000 - val_loss: 1.2410
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.1496 - val_accuracy: 0.5000 - val_loss: 1.2473
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step - accuracy: 1.0000 - loss: 0.1478 - val_accuracy: 0.5000 - val_loss: 1.2539
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 266ms/step - accuracy: 1.0000 - loss: 0.1460 - val_accuracy: 0.5000 - val_loss: 1.2602
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.1442 - val_accuracy: 0.5000 - val_loss: 1.2667
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.1426 - val_accuracy: 0.5000 - val_loss: 1.2729
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - accuracy: 1.0000 - loss: 0.1409 - val_accuracy: 0.5000 - val_loss: 1.2782
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 220ms/step - accuracy: 1.0000 - loss: 0.1392 - val_accuracy: 0.5000 - val_loss: 1.2837
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 215ms/step - accuracy: 1.0000 - loss: 0.1376 - val_accuracy: 0.5000 - val_loss: 1.2895
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - accuracy: 1.0000 - loss: 0.1360 - val_accuracy: 0.5000 - val_loss: 1.2955
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 1.0000 - loss: 0.1344 - val_accuracy: 0.5000 - val_loss: 1.3018
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 1.0000 - loss: 0.1328 - val_accuracy: 0.5000 - val_loss: 1.3072
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.1313 - val_accuracy: 0.5000 - val_loss: 1.3129
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 1.0000 - loss: 0.1298 - val_accuracy: 0.5000 - val_loss: 1.3189
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 1.0000 - loss: 0.1283 - val_accuracy: 0.5000 - val_loss: 1.3250
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - accuracy: 1.0000 - loss: 0.1268 - val_accuracy: 0.5000 - val_loss: 1.3313
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 279ms/step - accuracy: 1.0000 - loss: 0.1253 - val_accuracy: 0.5000 - val_loss: 1.3367

In [30]:
# Create a new customer's data as a DataFrame
new_customer = pd.DataFrame({
    'CreditScore': [600],
    'Geography': ['France'],
    'Gender': ['Male'],
    'Age': [40],
    'Balance': [62000],
    'EstimatedSalary': [50000]
})

# Encode and match training columns
new_customer['Gender'] = le.transform(new_customer['Gender'])
new_customer = pd.get_dummies(new_customer, columns=['Geography'], drop_first=True)

# Add any missing columns that exist in X
for col in X.columns:
    if col not in new_customer.columns:
        new_customer[col] = 0

# Reorder columns to match training data
new_customer = new_customer[X.columns]

# (Optional) Scale data if you used a scaler before training
# If you didn’t, skip these two lines.
# from sklearn.preprocessing import StandardScaler
# new_customer = scaler.transform(new_customer)

# Predict
pred = bank_model.predict(new_customer)

# Output
if pred[0][0] > 0.5:
    print("Customer will leave.")
else:
    print("Customer will not leave.")

print(f"Predicted probability: {pred[0][0]:.4f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step
Customer will leave.
Predicted probability: 1.0000

In [31]:
# Create a new customer's data as a DataFrame
new_customer = pd.DataFrame({
    'CreditScore': [600],
    'Geography': ['France'],
    'Gender': ['Male'],
    'Age': [40],
    'Balance': [62000],
    'NumOfProducts': [1],
    'EstimatedSalary': [50000]
})

# Encode Gender using the fitted LabelEncoder
new_customer['Gender'] = le.transform(new_customer['Gender'])

# One-hot encode Geography and drop first to match training setup
new_customer = pd.get_dummies(new_customer, columns=['Geography'], drop_first=True)

# Add any missing columns that exist in X but not in new_customer
for col in X.columns:
    if col not in new_customer.columns:
        new_customer[col] = 0

# Reorder columns to match the training set
new_customer = new_customer[X.columns]

# Scale using the same scaler fitted on the training data
new_scaled = scaler.transform(new_customer)

# Predict using the trained model
pred = bank_model.predict(new_scaled)

# Display prediction
if pred[0][0] > 0.5:
    print("Customer will leave.")
else:
    print("Customer will not leave.")

print(f"Predicted probability: {pred[0][0]:.4f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step
Customer will not leave.
Predicted probability: 0.2281